[Project] Add first task
Krekep/formal-lang-course pull request #1
Opened 2021-09-05 17:45 UTC by Krekep

- Add tests launch
- Add method for getting graph info
- Add method for create and export graph
- Add user console input handler
- Add tests for graphs method

2021-09-06 13:10 UTC, vdshk requested changes
Также есть пара глобальных замечаний.

* Запускаться `REPL` должен через `python -m project`. Сейчас так не работает.

* >   - [ ] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах.

    Именно **по имени**. В наборе данных у графов есть имена. Такие как `geospecies`, `pizza`, `enzyme`. См. [Get a real graph](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#get-a-real-graph)
    
* Копируйте из `tasks` полностью описание задачи в комментарий вашего PR и проставляйте чекбоксики, пожалуйста. Так будет и вам и мне проще видеть, что требовалось сделать и что уже сделано.

* Не забудьте написать в `project/README.md` как запускать ваше **консольное приложение**.

* Убедитесь, что ваши тесты покрывают все возможные крайние случаи.
    
> Мой комментарий на русском языке, так как курс читается на русском языке.
Если вы согласны перейти на английский, напишите мне об этом, пожалуйста, в комментариях.

2021-09-06 13:10 UTC, vadyushkins commented on .github/workflows/tests.yml
> +        python-version: [ 3.8 ]
Добавьте в матрицу `ubuntu-latest`, `macos-latest`, `windows-latest`, чтобы тестировать ваше решение на всех платформах. Мы в задачах будем использовать только кросс-платформенные библиотеки, поэтому проблем не будет.

2021-09-06 13:10 UTC, vadyushkins commented on project/bridge.py
> +import networkx
```suggestion
import networkx as nx
```

2021-09-06 13:10 UTC, vadyushkins commented on project/__main__.py
> +    console.run_console()
Запустил из корня репозитория `python3 -m project` и получил
```
AttributeError: module 'console' has no attribute 'run_console'
```
Кажется так не должно быть. Или я что-то сделал не так?

2021-09-06 13:10 UTC, vadyushkins commented on project/bridge.py
> +__all__ = ["graph_info", "create_and_export", "shutdown"]
По заданию у вас должны быть следующие команды. (названия примерные)
```suggestion
command_names = ["get_graph_info", "create_two_cycles_graph", "save_to_dot", "quit"]
```

2021-09-06 13:10 UTC, vadyushkins commented on project/bridge.py
> +    """
Используйте [`NumPy docstrings`](https://numpydoc.readthedocs.io/en/latest/format.html).
Минимально требуется: `1. Short summary`, `4. Parameters`, `5. Returns` или `6. Yields`

2021-09-06 13:10 UTC, vadyushkins commented on project/bridge.py
> +    """
И так для всех функций и классов.

2021-09-06 13:10 UTC, vadyushkins commented on project/bridge.py
> +    print("Labels: ", *(info[2]))
Старайтесь разделять пыстуми строками осмысленные блоки текста, а не слепливать всё в одно полотно.

```suggestion
    if len(arg) != 1:
        raise Exception("Invalid amount of arguments!")
        
    filename = arg[0]
    name, extension = filename.split(".")
    
    if not _is_file(filename):
        raise Exception("No such file exists!")
        
    if extension != "dot":
        raise Exception("Wrong extension of file!")
        
    graph = _read_graph(filename)
    info = utils.get_graph_info(graph)
    
    print("Graph information:")
    print("Number of nodes: ", info[0])
    print("Number of edges: ", info[1])
    print("Labels: ", *(info[2]))
```

2021-09-06 13:10 UTC, vadyushkins commented on project/test.dot
> +digraph  {
Непонятно для чего используется этот файл. Да и папка `resources` в целом.
Если вы хотите написать тест, проверяющий, что вы правильно сохраняете файл в формате DOT, тот этот файл должен быть в папке `tests`. Желательно в `tests/data`.

2021-09-06 13:10 UTC, vadyushkins commented on requirements.txt
> +networkx
`networkx` уже есть в зависимостях у `cfpq_data`. Почему вы его добавили?
```suggestion
```

2021-09-06 13:10 UTC, vadyushkins commented on tests/test_utils.py
> +    print("basic teardown module")
Кажется здесь этого быть не должно

2021-09-06 13:10 UTC, vadyushkins commented on tests/test_utils.py
> +    assert g_info[2] == {"a", "b"}
В unit тестах лучше придерживаться правила один assert на тест.

2021-09-06 13:10 UTC, vadyushkins commented on tests/test_utils.py
> +    )
Что этот тест проверяет?
Как минимум стоит проверять то, что тот граф, который вы сохраняете, совпадает с тем, что вы ожидаете увидеть как он сохранится. По сути должен быть `graph_expected.dot` в `tests/data`.

2021-09-08 17:09 UTC, Krekep commented on tests/test_utils.py
> +    )
Исправлено.

2021-09-08 17:13 UTC, Krekep commented on tests/test_utils.py
> +    assert g_info[2] == {"a", "b"}
Исправлено.

2021-09-08 17:13 UTC, Krekep commented on tests/test_utils.py
> +    print("basic teardown module")
Исправлено.

2021-09-08 17:13 UTC, Krekep commented on requirements.txt
> +networkx
Исправлено.

2021-09-08 17:13 UTC, Krekep commented on project/test.dot
> +digraph  {
Исправлено.

2021-09-08 17:13 UTC, Krekep commented on project/bridge.py
> +    print("Labels: ", *(info[2]))
Исправлено.

2021-09-08 17:14 UTC, Krekep commented on project/bridge.py
> +    """
Исправлено.

2021-09-08 17:14 UTC, Krekep commented on project/bridge.py
> +__all__ = ["graph_info", "create_and_export", "shutdown"]
Исправлено.

2021-09-08 17:14 UTC, Krekep commented on project/__main__.py
> +    console.run_console()
Исправлено.

2021-09-08 17:14 UTC, Krekep commented on project/bridge.py
> +import networkx
А почему именно так? Просто потому что так принято?

2021-09-08 17:14 UTC, Krekep commented on project/bridge.py
> +import networkx
Исправлено.

2021-09-08 17:16 UTC, Krekep commented on .github/workflows/tests.yml
> +        python-version: [ 3.8 ]
Исправлено.

2021-09-08 17:17 UTC, Krekep commented
# Задача 1. Инициализация рабочего окружения

* **Мягкий дедлайн**: 05.09.2021, 23:59
* **Жёсткий дедлайн**: 08.09.2021, 23:59
* Полный балл: 5

## Задача

- [x] Сделать публичный `fork` данного репозитория.
- [x] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/18DhYG5CuOrN4A5b5N7-mEDfDkc-7BuXF3Qsu6HD-lks/edit?usp=sharing).
- [x] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в [таблицу](https://docs.google.com/spreadsheets/d/18DhYG5CuOrN4A5b5N7-mEDfDkc-7BuXF3Qsu6HD-lks/edit?usp=sharing))
- [x] Реализовать консольное приложение, предоставляющее перечисленные ниже возможности. Для работы с графами использовать [cfpq-data](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#graphs). Данное приложение в дальнейшем будет расширяться. Функции приложения, которые необходимо реализовать:
  - [x] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах.
  - [x] По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).
- [x] Добавить необходимые тесты.
- [x] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.

2021-09-13 08:18 UTC, vdshk approved these changes
Молодец :+1:

> Советую, чтобы не сохранять все исправления в истории, сделать `Squash and merge`

Замечания на будущее:
1. Старайтесь в `docstrings` разделять блоки `Parameters`, `Returns`, etc.
2. Исправьте `from . import ...` на [правильный вариант по PEP8](https://www.python.org/dev/peps/pep-0008/#imports)

2021-09-13 18:20 UTC, merged