Task4
Krekep/formal-lang-course pull request #14
Opened 2022-10-02 19:38 UTC by Krekep

# Задача 4. Регулярные запросы для нескольких стартовых вершин

* **Мягкий дедлайн**: 02.10.2022, 23:59
* **Жёсткий дедлайн**: 05.10.2022, 23:59
* Полный балл: 5

## Задача

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** достижимости с регулярными ограничениями для нескольких стартовых вершин.
  - Предусмотрите два варианта задачи:
    - Для указанного множества стартовых вершин найти множество достижимых.
    - Для каждой вершины из указанного множества найти множество достижимых вершин.
- [x] На основе реализованной функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе и вариант решаемой задачи.
  - Для конструирования регулярного запроса и графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [x] Добавить необходимые тесты.

2022-10-04 16:51 UTC, rustam-azimov requested changes

2022-10-04 16:51 UTC, rustam-azimov commented on project/rpq.py
> +        print(node_from, node_to, graph.get_edge_data(node_from, node_to)[0]["label"])
Не думаю что хотим печатать что то.

2022-10-04 16:51 UTC, rustam-azimov commented on project/rpq.py
> +            for vertica in row.indices:
Проверьте что есть слово vertica, я только vertex использовал всегда.

2022-10-04 16:51 UTC, rustam-azimov commented on project/rpq.py
> +        res.add((frozenset(start_vertices), frozenset(reachable_vertices)))
Предлагаю возвращать просто множество достижимых или множество пар достижимых (i, j) в случае separated = true.

2022-10-04 16:51 UTC, rustam-azimov commented on project/rpq.py
> +        Adjacency matrix where (i, j) = True if `i` in v_src and j not in v_src and w is reachable from v_src
Запутался, что значит тут w? И почему j not in v_src?

2022-10-05 13:56 UTC, Krekep commented on project/rpq.py
> +        print(node_from, node_to, graph.get_edge_data(node_from, node_to)[0]["label"])
Да, забыл удалить после дебага
Исправил

2022-10-05 13:56 UTC, Krekep commented on project/rpq.py
> +            for vertica in row.indices:
Исправил

2022-10-05 13:57 UTC, Krekep commented on project/rpq.py
> +        res.add((frozenset(start_vertices), frozenset(reachable_vertices)))
Наверное, Вы перепутали случай с separated, потому что код выделен для случая separated = false
Исправил, теперь возвращает просто множество достижимых

2022-10-05 13:59 UTC, Krekep commented on project/rpq.py
> +        Adjacency matrix where (i, j) = True if `i` in v_src and j not in v_src and w is reachable from v_src
С конспекта криво переписал. С условием j not in v_src я, кажется, в самом деле ошибся. w это j
Исправил

2022-10-09 11:08 UTC, rustam-azimov approved these changes

2022-10-09 17:04 UTC, merged