Complete task9
Krekep/formal-lang-course pull request #20
Opened 2022-11-13 19:48 UTC by Krekep

# Задача 9. Алгоритм Хеллингса

* **Мягкий дедлайн**: 13.11.2022, 23:59
* **Жёсткий дедлайн**: 16.11.2022, 23:59
* Полный балл: 5

## Задача

- [x] Реализовать **функцию**, основанную на алгоритме Хеллингса, решающую задачу достижимости между всеми парами вершин для заданного графа и заданной КС грамматики.
  - Результат работы функции --- множество троек вида (вершина, нетерминал, вершина).
  - Предусмотрите возможность получать граф из различных источников в различных форматах.
  - Предусмотрите возможность получать грамматику из различных источников (из файла, как результат работы других функций).
  - Для преобразования грамматики в ОНФХ использовать результаты предыдущих работ.
- [x] На основе предыдущей функции реализовать функцию, позволяющую решать задачу достижимости для заданного набора стартовых и финальных вершин, и заданного нетерминала.
- [x] Добавить необходимые тесты.

2022-11-15 08:40 UTC, rustam-azimov requested changes

2022-11-15 08:40 UTC, rustam-azimov commented on project/cfpq.py
> +    Constrained transitive closure by hellings algorithm
Hellings

2022-11-15 08:40 UTC, rustam-azimov commented on project/cfpq.py
> +        Set of triple of start vertex, symbols and final vertex
Set of triples (start vertex, nonterminal symbol, final vertex)

2022-11-15 08:40 UTC, rustam-azimov commented on project/cfpq.py
> +    start_variable: Variable = Variable("S"),
Не помню, если у Вас везде нетерминалы назывались variable то ок. Но иначе лучше продолжать называть nonterminal.

2022-11-15 08:40 UTC, rustam-azimov commented on project/cfpq.py
> +    Performs context-free path querying in graph with given context free grammar
context-free

2022-11-15 08:40 UTC, rustam-azimov commented on project/cfpq.py
> +    start_nodes: list[any] = None,
Может лучше множества использовать?

2022-11-15 08:40 UTC, rustam-azimov commented on project/cfpq.py
> +def hellings(graph: MultiDiGraph, cfg: CFG) -> set[tuple]:
Добавить разные форматы для графов и грамматик
Предусмотрите возможность получать граф из различных источников в различных форматах.
Предусмотрите возможность получать грамматику из различных источников (из файла, как результат работы других функций).

2022-11-15 15:41 UTC, Krekep commented on project/cfpq.py
> +    Constrained transitive closure by hellings algorithm
Исправил

2022-11-15 15:41 UTC, Krekep commented on project/cfpq.py
> +        Set of triple of start vertex, symbols and final vertex
Исправил

2022-11-15 15:41 UTC, Krekep commented on project/cfpq.py
> +    start_variable: Variable = Variable("S"),
Почти везде было написано просто `start`, только в одном месте было написано `start_symbol`, изменил на `start_symbol`

2022-11-15 15:42 UTC, Krekep commented on project/cfpq.py
> +    Performs context-free path querying in graph with given context free grammar
Исправил

2022-11-15 15:42 UTC, Krekep commented on project/cfpq.py
> +    start_nodes: list[any] = None,
Исправил

2022-11-15 15:43 UTC, Krekep commented on project/cfpq.py
> +def hellings(graph: MultiDiGraph, cfg: CFG) -> set[tuple]:
Исправил
Теперь граф передавать не только как объект `MultiDiGraph`, но и по имени из `cfpq_data` датасета
Грамматику можно передавать не только как объект `CFG`, но и по строковому представлению и по пути до файла с ней

2022-11-24 10:10 UTC, rustam-azimov approved these changes

2022-11-26 17:48 UTC, merged