Complete task 2
Krekep/formal-lang-course pull request #3
Opened 2021-09-12 16:09 UTC by Krekep

# Задача 2. Построение детерминированного конечного автомата по регулярному выражению

* **Мягкий дедлайн**: 12.09.2021, 23:59
* **Жёсткий дедлайн**: 15.09.2021, 23:59
* Полный балл: 2

## Задача

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения.](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
- [x] Добавить необходимые тесты.

2021-09-12 17:09 UTC, Krekep commented
Кода из первой задачи нет, т.к. она ещё не одобрена.

2021-09-13 09:17 UTC, vdshk requested changes
Глобально всё хорошо :+1:
Но есть пара небольших замечаний, которые стоит поправить ;)

> Думаю стоит сначала закрыть первую задачу, потом смерджить ее в `main` и в эту ветку с `main`'а. Чтобы лишних файлов в ПР не было

2021-09-13 09:17 UTC, vdshk commented on tests/test_regex.py
> +    ]
Посмотрите, пожалуйста, на [`@pytest.mark.parametrize`](https://docs.pytest.org/en/6.2.x/parametrize.html) и добавьте больше регулярных выражений (с крайними случаями, например `regex = ""`)

2021-09-13 09:17 UTC, vdshk commented on tests/test_regex.py
> +        assert not dfa.accepts(word)
Также стоит добавить тесты :
* на минимальность построенного ДКА
* на проверку того, что тот ДКА, который вы получаете из функции совпадает с ДКА, который вы ожидаете получить
* на проверку того, что если регулярное выражение неправильное, то вы выдадите нужный `Exception`

2021-09-14 10:09 UTC, merged