Complete task 3
Krekep/formal-lang-course pull request #8
Opened 2021-09-17 18:33 UTC by Krekep

# Задача 3. Построение недетерминированного конечного автомата по графу

* **Мягкий дедлайн**: 19.09.2021, 23:59
* **Жёсткий дедлайн**: 22.09.2021, 23:59
* Полный балл: 2

## Задача

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения недетерминированного конечного автомата по [графу](https://networkx.org/documentation/stable/reference/classes/multidigraph.html), в том числе по любому из графов, которые можно получить, пользуясь функциональностью, реализованной в [Задаче 1](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task1.md) (загруженный из датасета по имени граф, сгенерированный синтетический граф). Предусмотреть возможность указывать стартовые и финальные вершины. Если они не указаны, то считать все вершины стартовыми и финальными.
- [x] Добавить необходимые тесты.

2021-09-20 11:29 UTC, vdshk requested changes
В целом всё хорошо :+1: 
Только добавьте, пожалуйста, больше разных графов (граф без вершин, граф на 1 вершине, граф без ребер, т.п.) :eyes: 
И CI всё-таки пройдите

2021-09-22 11:13 UTC, vdshk commented
Предлагаю уменьшить ДФА в `test_get_min_dfa`. Так как `pyformlang` недетерминированным образом строит мин ДФА.

Без пройденного CI сложно засчитывать задачу :)

2021-09-22 11:25 UTC, Krekep commented
Этот тест через раз проходил, при чём на он одновременно проходил и не проходил на пуше и пулл реквесте :(

2021-09-22 11:41 UTC, vdshk approved these changes
Зачтено :+1:

2021-09-22 11:44 UTC, merged